var words = [
  'doughnuts'
  , 'beignets'
  , 'fried Oreos'
  , 'fried Twinkies'
  , 'chicken-fried steaks'
  , 'brussel sprouts'
  , 'fried Snickers'
  , 'french fries'
  , 'shrimp po-boys'
  , 'angels on horseback'
  , 'clam strips and cocktail sauce'
  , 'fried farm eggs'
  , 'cheese fries and gravy'
  , 'chicken cutlets'
  , 'veal parmigiana'
  , 'baklava'
  , 'eggplant parm'
  , 'extra hot buffalo wings'
  , 'croquettes'
  , 'bacalao'
  , 'onion rings'
  , 'pork-stuffed egg rolls'
  , 'empanadas'
  , 'falafel'
  , 'plantain chips'
  , 'fish and chips'
  , 'pommes frites and aioli'
  , 'fried pickles'
  , 'corndogs'
  , 'General Tso\'s chicken'
  , 'kids chicken nuggets'
  , 'calamari'
  , 'shrimp tempura'
  , 'papadums'
  , 'krupuks'
  , 'Kappa Ebisen'
  , 'veggie tempura'
  , 'tortilla chips'
  , 'crab rangoons'
  , 'elephant ears'
  , 'popovers'
  , 'corn fritters'
  , 'pork dumplings'
  , 'mozzarella sticks'
  , 'crawfish puffs'
  , 'sopapillas'
  , 'scallion pancakes'
  , 'soft-shelled crabs'
  , 'Cajun crabcakes'
  , 'jalapeño poppers'
  , 'crawfish tails'
  , 'bloomin\' onions'
  , 'chalupas'
  , 'taquitos'
  , 'Lay\'s'
  , 'Scotch eggs'
  , 'gator bites'
  , 'horseradish sauce'
  , 'kroketten'
  , 'jin deui'
  , 'puri'
  , 'samosas'
  , 'namak para'
  , 'zeppoles'
  , 'Philly scrapple'
  , 'churros'
  , 'funnel cakes'
  , 'latkes'
  , 'knishes'
  , 'bitterballen'
  , 'Mrs. Wheat\'s meat pies'
  , 'chicken fingers with Cane\'s sauce'
  , 'crawfish pies'
  , 'Hubig\'s pies'
  , 'pakoras'
  , 'hush puppies \'n\' tartar sauce'
  , 'wontons'
  , 'far-far'
  , 'pita chips'
];
